{{- if $.Values.gangplank.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gangplank.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gangplank.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.gangplank.sensitiveEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
