{{- if $.Values.gangplank.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gangplank.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gangplank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gangplank.service.type }}
  ports:
    - port: {{ .Values.gangplank.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gangplank.selectorLabels" . | nindent 4 }}
{{- end }}
