{{- if $.Values.gangplank.enabled }}
  {{- if .Values.gangplank.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gangplank.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gangplank.labels" . | nindent 4 }}
  {{- with .Values.gangplank.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gangplank.serviceAccount.automount }}
  {{- end }}
{{- end }}
